services:
  web:
    build: .
    working_dir: /data
    command: python api.py
    links:
      - db
    volumes:
      - .:/data
    ports:
      - "5008:5008"

  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: senha
    ports:
      - "3307:3307"